[project]
name = "machine-learning-zoomcamp-2026-course-deployment-module-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Muhammad Waqas Khan", email = "combatant936@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.142.1",
    "scikit-learn>=1.9.1",
    "uvicorn>=0.54.0",
]

[project.scripts]
machine-learning-zoomcamp-2026-course-deployment-module-project = "machine_learning_zoomcamp_2026_course_deployment_module_project:main"

[build-system]
requires = ["uv_build>=0.12.21,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "requests>=2.34.2",
]
